#add the linters you want stickler to use for this project
linters:
  eslint:
    # indicate where is the config file for stylelint
    config: "./.eslintrc.json"

  rubocop:
    display_cop_names: true
    config: "./rubocop.yml"

files:
  ignore:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Procfile"